// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvqaqzdjhfswtkwfkuzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2cWFxemRqaGZzd3Rrd2ZrdXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MTY3MTUsImV4cCI6MjA2MTE5MjcxNX0.QkBoyrzgAbi4gT6B3UK1Xn9ZRgyzacCcwjFD1itPv1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);